import { SerialPort } from "serialport";
import { ReadlineParser } from "@serialport/parser-readline";
import { buildSettingsFrame, FrameParser, decodeRfid } from "./waveshare.mjs";
const all = await SerialPort.list();
const mod = all.find(p => (p.vendorId||"").toLowerCase()==="1a86");
const rdr = all.find(p => (p.vendorId||"").toLowerCase()==="0403");
console.log(`module=${mod?.path} reader=${rdr?.path}`);
let got=0, lastTx="(none)";
const sp = new SerialPort({ path: mod.path, baudRate: 2000000, dataBits:8, stopBits:1, parity:"none" });
const parser = new FrameParser(m=>{got++;const {reader,uid}=decodeRfid(m);console.log(`  >>> MODULE GOT #${got}: Reader ${reader} UID:"${uid}"`);});
sp.on("data", c=>parser.push(c));
sp.on("open", ()=>sp.write(buildSettingsFrame({bitrate:500000}), ()=>sp.drain(()=>{})));
const rp=new SerialPort({path:rdr.path,baudRate:115200});
rp.pipe(new ReadlineParser({delimiter:"\n"})).on("data",l=>{const t=l.trim(); if(t.startsWith("TX ")||t.includes("HEARTBEAT")) lastTx=t;});
let s=0; const iv=setInterval(()=>{s+=3;console.log(`[${s}s] reader: ${lastTx}  |  module got: ${got}`);},3000);
setTimeout(()=>{clearInterval(iv);console.log(`\n=== module got ${got} frames ===`);process.exit(0);},24000);
