import { SerialPort } from "serialport";
import { ReadlineParser } from "@serialport/parser-readline";
const all = await SerialPort.list();
const esp = all.find(p => (p.vendorId||"").toLowerCase()==="10c4");
const rdr = all.find(p => (p.vendorId||"").toLowerCase()==="0403");
console.log(`esp(rx)=${esp?.path} reader(tx)=${rdr?.path}`);
let got=0, lastTx="(none)";
const ep=new SerialPort({path:esp.path,baudRate:115200});
ep.pipe(new ReadlineParser({delimiter:"\n"})).on("data",l=>{const t=l.trim(); if(t.startsWith("GOT")){got++;console.log(`  >>> ESP RECEIVED #${got}: ${t}`);} else if(t.includes("RECEIVER")) console.log("ESP| "+t);});
const rp=new SerialPort({path:rdr.path,baudRate:115200});
rp.pipe(new ReadlineParser({delimiter:"\n"})).on("data",l=>{const t=l.trim(); if(t.startsWith("TX ")) lastTx=t;});
let s=0; const iv=setInterval(()=>{s+=3;console.log(`[${s}s] reader: ${lastTx}  |  ESP received: ${got}`);},3000);
setTimeout(()=>{clearInterval(iv);console.log(`\n=== ESP received ${got} frames from reader ===`);process.exit(0);},21000);
